services:
  imc-back:
    image: chillo.tech/imc-back:1.0.1
    container_name: imc-back
    restart: always
    ports:
      - 8383:8383
    networks:
      - imc-network
networks:
  imc-network:
    external: true
    name: imc-network
